/**
*	GLOBAL VARIABLES
*/

var UNIT = 20;
var DIRECTION_ENUM = {
	"LEFT":"LEFT",
	"RIGHT":"RIGHT",
	"UP":"UP",
	"DOWN":"DOWN",
	"TOP":"TOP",
	"BOTTOM":"BOTTOM",
	"DIAGONAL_TOP_LEFT":"DIAGONAL_TOP_LEFT",
	"DIAGONAL_TOP_RIGHT":"DIAGONAL_TOP_RIGHT",
	"DIAGONAL_BOTTOM_LEFT":"DIAGONAL_BOTTOM_LEFT",
	"DIAGONAL_BOTTOM_RIGHT":"DIAGONAL_BOTTOM_RIGHT",
};
var DirectionEnum = DIRECTION_ENUM;
var ACTION_ENUM = {
	MOVE:"move",
	JUMP:"jump",
	COOK:"cook",
	SLEEP:"sleep",
};
var ACTION_STATE_ENUM = {
	TOSTART:"TOSTART",
	STARTED:"STARTED",
	TOSTOP:"TOSTOP",
	STOPED:"STOPED",
	TOSPAUSE:"TOPAUSE",
	PAUSE:"PAUSE",
	TOFINISH:"TOFINISH",
	FINISHED:"FINISHED",
};
var MOVE_STATE_ENUM = {
	STOPPED:"STOPPED",
	MOVING:"MOVING",
};


var MOVE_FINISHED = -1;
var MOVE_ON = 0;
var MOVE_WAIT = 1;

var FOOT_STEP_DURATION = 100;
var CHECK_DURATION = 200;
