/**
*	GLOBAL VARIABLES
*/

var UNIT = 20;
var DIRECTION_ENUM = {"TOP":"TOP","LEFT":"LEFT","RIGHT":"RIGHT","BOTTOM":"BOTTOM","DIAGONAL_TOP_LEFT":"DIAGONAL_TOP_LEFT","DIAGONAL_TOP_RIGHT":"DIAGONAL_TOP_RIGHT","DIAGONAL_BOTTOM_LEFT":"DIAGONAL_BOTTOM_LEFT","DIAGONAL_BOTTOM_RIGHT":"DIAGONAL_BOTTOM_RIGHT"};
var DirectionEnum = DIRECTION_ENUM;
var ACTION_ENUM = {
	MOVE:"move",
	JUMP:"jump",
	COOK:"cook",
	SLEEP:"sleep",
};

var MOVE_FINISHED = -1;
var MOVE_ON = 0;
var STEP_DURATION = 800;
var FOOT_STEP_DURATION = 150;
var CHECK_DURATION = 100;
