var TemplateOccupationHelper=new Object();
TemplateOccupationHelper.getTop=function(type){if(TemplateOccupation[type]===undefined){return "";}return TemplateOccupation[type].cornerTTL+""+TemplateOccupation[type].topL+""+TemplateOccupation[type].topR+""+TemplateOccupation[type].cornerTTR;};
TemplateOccupationHelper.getLeft=function(type){if(TemplateOccupation[type]===undefined){return "";}return TemplateOccupation[type].cornerTLL+""+TemplateOccupation[type].leftT+""+TemplateOccupation[type].leftB+""+TemplateOccupation[type].cornerBLL;};
TemplateOccupationHelper.getRight=function(type){if(TemplateOccupation[type]===undefined){return "";}return TemplateOccupation[type].cornerTRR+""+TemplateOccupation[type].rightT+""+TemplateOccupation[type].rightB+""+TemplateOccupation[type].cornerBRR;};
TemplateOccupationHelper.getBottom=function(type){if(TemplateOccupation[type]===undefined){return "";}return TemplateOccupation[type].cornerBRR+""+TemplateOccupation[type].bottomL+""+TemplateOccupation[type].bottomR+""+TemplateOccupation[type].cornerBBR;};
TemplateOccupationHelper.canAccess=function(direction){return false;};

TemplateOccupationHelper.getBrushesTypes=function(){var result=new Array("square","round");return result;};
TemplateOccupationHelper.order={primary:0,secondary:1};
/**
*	/ ! \ NE PAS MODIFIER le contenu de ce tableau sans impacter l'ensemble des images des tiles
*	/ ! \ pour toute modification passer par l'éditeur
*	occupations du template : 
* 		_ principale:0 ( "Herbe" dans l'éditeur)
*		_ secondaire:1 ( "Eau" dans l'éditeur)
*
*/
var TemplateOccupation=new Object();
TemplateOccupation['1_1']={"cornerTTL":1,"cornerTLL":1,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"1_1"};
TemplateOccupation['2_1']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":1,"cornerTRR":1,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":1,"cornerBLL":1,"leftB":0,"leftT":0,"isObstable":0,"UID":"2_1"};
TemplateOccupation['3_1']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"3_1"};
TemplateOccupation['4_1']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":1,"isObstable":0,"UID":"4_1"};
TemplateOccupation['5_1']={"cornerTTL":1,"cornerTLL":0,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"5_1"};
TemplateOccupation['6_1']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":0,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":1,"isObstable":1,"UID":"6_1"};
TemplateOccupation['7_1']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"7_1"};
TemplateOccupation['8_1']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"8_1"};
TemplateOccupation['9_1']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"9_1"};
TemplateOccupation['10_1']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"10_1"};
TemplateOccupation['11_1']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"11_1"};
TemplateOccupation['12_1']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"12_1"};
TemplateOccupation['13_1']={"cornerTTL":1,"cornerTLL":1,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"13_1"};
TemplateOccupation['14_1']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"14_1"};
TemplateOccupation['15_1']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"15_1"};
TemplateOccupation['16_1']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":1,"isObstable":0,"UID":"16_1"};
TemplateOccupation['17_1']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":0,"isObstable":1,"UID":"17_1"};
TemplateOccupation['18_1']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":0,"leftT":0,"isObstable":1,"UID":"18_1"};
TemplateOccupation['19_1']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":0,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"19_1"};
TemplateOccupation['20_1']={"cornerTTL":1,"cornerTLL":0,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"20_1"};
TemplateOccupation['1_2']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"1_2"};
TemplateOccupation['2_2']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":0,"UID":"2_2"};
TemplateOccupation['3_2']={"cornerTTL":0,"cornerTLL":1,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"3_2"};
TemplateOccupation['4_2']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":0,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":0,"isObstable":0,"UID":"4_2"};
TemplateOccupation['5_2']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"5_2"};
TemplateOccupation['6_2']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":0,"isObstable":1,"UID":"6_2"};
TemplateOccupation['7_2']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":1,"leftT":1,"isObstable":0,"UID":"7_2"};
TemplateOccupation['8_2']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":1,"isObstable":0,"UID":"8_2"};
TemplateOccupation['9_2']={"cornerTTL":0,"cornerTLL":0,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":0,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"9_2"};
TemplateOccupation['10_2']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":0,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"10_2"};
TemplateOccupation['11_2']={"cornerTTL":0,"cornerTLL":0,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"11_2"};
TemplateOccupation['12_2']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":0,"isObstable":1,"UID":"12_2"};
TemplateOccupation['13_2']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"13_2"};
TemplateOccupation['14_2']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"14_2"};
TemplateOccupation['15_2']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":0,"isObstable":1,"UID":"15_2"};
TemplateOccupation['16_2']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":0,"UID":"16_2"};
TemplateOccupation['17_2']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":1,"isObstable":1,"UID":"17_2"};
TemplateOccupation['18_2']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"18_2"};
TemplateOccupation['19_2']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":0,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"19_2"};
TemplateOccupation['20_2']={"cornerTTL":0,"cornerTLL":1,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"20_2"};
TemplateOccupation['1_3']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"1_3"};
TemplateOccupation['2_3']={"cornerTTL":1,"cornerTLL":0,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":0,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"2_3"};
TemplateOccupation['3_3']={"cornerTTL":0,"cornerTLL":1,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":0,"UID":"3_3"};
TemplateOccupation['4_3']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"4_3"};
TemplateOccupation['5_3']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"5_3"};
TemplateOccupation['6_3']={"cornerTTL":1,"cornerTLL":0,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":0,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"6_3"};
TemplateOccupation['7_3']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":0,"isObstable":0,"UID":"7_3"};
TemplateOccupation['8_3']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":0,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":0,"UID":"8_3"};
TemplateOccupation['9_3']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"9_3"};
TemplateOccupation['10_3']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"10_3"};
TemplateOccupation['11_3']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"11_3"};
TemplateOccupation['12_3']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":1,"isObstable":1,"UID":"12_3"};
TemplateOccupation['13_3']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"13_3"};
TemplateOccupation['14_3']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"14_3"};
TemplateOccupation['15_3']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"15_3"};
TemplateOccupation['16_3']={"cornerTTL":0,"cornerTLL":0,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"16_3"};
TemplateOccupation['17_3']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"17_3"};
TemplateOccupation['18_3']={"cornerTTL":1,"cornerTLL":1,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"18_3"};
TemplateOccupation['19_3']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"19_3"};
TemplateOccupation['20_3']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"20_3"};
TemplateOccupation['1_4']={"cornerTTL":0,"cornerTLL":1,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":0,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"1_4"};
TemplateOccupation['2_4']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"2_4"};
TemplateOccupation['3_4']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":0,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"3_4"};
TemplateOccupation['4_4']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"4_4"};
TemplateOccupation['5_4']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":0,"UID":"5_4"};
TemplateOccupation['6_4']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":0,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"6_4"};
TemplateOccupation['7_4']={"cornerTTL":1,"cornerTLL":1,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"7_4"};
TemplateOccupation['8_4']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":0,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":0,"leftT":0,"isObstable":0,"UID":"8_4"};
TemplateOccupation['9_4']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"9_4"};
TemplateOccupation['10_4']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"10_4"};
TemplateOccupation['11_4']={"cornerTTL":0,"cornerTLL":0,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"11_4"};
TemplateOccupation['12_4']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":1,"leftT":1,"isObstable":1,"UID":"12_4"};
TemplateOccupation['13_4']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"13_4"};
TemplateOccupation['14_4']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":1,"leftT":1,"isObstable":1,"UID":"14_4"};
TemplateOccupation['15_4']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":1,"isObstable":1,"UID":"15_4"};
TemplateOccupation['16_4']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":0,"UID":"16_4"};
TemplateOccupation['17_4']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":1,"UID":"17_4"};
TemplateOccupation['18_4']={"cornerTTL":1,"cornerTLL":1,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":0,"rightB":0,"cornerBBR":0,"cornerBRR":0,"bottomR":0,"bottomL":0,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"18_4"};
TemplateOccupation['19_4']={"cornerTTL":0,"cornerTLL":0,"topL":0,"topR":0,"cornerTTR":0,"cornerTRR":0,"rightT":0,"rightB":0,"cornerBBR":1,"cornerBRR":1,"bottomR":0,"bottomL":0,"cornerBBL":0,"cornerBLL":0,"leftB":0,"leftT":0,"isObstable":0,"UID":"19_4"};
TemplateOccupation['20_4']={"cornerTTL":0,"cornerTLL":0,"topL":1,"topR":1,"cornerTTR":1,"cornerTRR":1,"rightT":1,"rightB":1,"cornerBBR":1,"cornerBRR":1,"bottomR":1,"bottomL":1,"cornerBBL":1,"cornerBLL":1,"leftB":1,"leftT":1,"isObstable":1,"UID":"20_4"};
